version: '2'
services:
  nginx:
    container_name: cronos-example-nginx
    build:
      context: ./docker/nginx
    volumes:
      - "./docker/nginx/html:/usr/share/nginx/html"
      - "./docker/nginx/shell:/shell"
    ports:
      - "8083:80"
    restart: always

  cron:
    container_name: cronos-example-cron
    image: litvinab/cronos:v0.1.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./docker/cronos/crontabs:/etc/crontabs"
    restart: always
